config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'wellcome/index'
  

  resources :notenotes

  authenticated :user do
    root 'notenotes#index', as: :user_root
  end
   root 'wellcome#index'
 
end

app/models/notenote.rb
class Notenote < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :notenotes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notenotes_controller.rb
class NotenotesController < ApplicationController
	before_action :set_note, only:[:show, :edit, :update, :destroy]
	before_action :authenticate_user!
	def index
		@note = Notenote.where(user_id: current_user)
		
	end
	def show
		
	end
	def new
		@note= current_user.notenotes.build
	end
	def create
		@note = current_user.notenotes.build(note_params)
		if @note.save
			redirect_to @note, notice: 'note was successfully created'
		else
			render 'new'
		end
		
	end
	def edit
		
	end
	def update
		@note.update(note_params)
		if @note.save
			redirect_to @note, notice:'was update'
			else
				render'edit'
			
		end
	end
	def destroy
		@note.destroy
		redirect_to notenotes_path
	end

	private
	def set_note
		
		@note= current_user.notenotes.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_to root_path, notice:"You don't have permission."
		
	end
	def note_params
		params.require(:notenote).permit(:title,:content)
	end
end

app/controllers/wellcome_controller.rb
class WellcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notenotes_helper.rb
module NotenotesHelper
end

app/helpers/wellcome_helper.rb
module WellcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
	%title NoteNote | Online Notebook Application
	= favicon_link_tag 'dh_logo.png'
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
	%link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css", rel: "stylesheet", integrity: "sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1", crossorigin: "anonymous"}
%body
	%header
		.header_inner
			= link_to image_tag( 'DH-logo-gold.png'), root_path, id: "logo"
			%nav
				- if user_signed_in?
					= link_to "New Note", new_notenote_path
					= link_to "Sign Out", destroy_user_session_path, method: :delete
				- else
					= link_to "Log In", new_user_session_path
	%p.notice= notice
	%p.alert= alert

	= yield

app/views/notenotes/_form.html.haml
= form_for @note, htm:{:multipart=>true} do |f|
	= f.text_field :title, input_html:{class:'form-control'}
	= f.text_area :content, input_html:{class:'form-control'}
	=f.button :submit, class:'button'

app/views/notenotes/edit.html.haml
.wrapper_with_padding
	%h1 Edit Note
	=render 'form'

app/views/notenotes/index.html.haml
.wrapper_with_padding
	#notes.clearfix
		- unless @note.blank?
			- @note.each do |note|
				%a{ href: (url_for [note])}
					.note
						%p.title= note.title
						%p.date= time_ago_in_words(note.created_at)
		- else
			%h2 Add a Note
			%p It appears you haven't created any notes yet... Lets fix that. Why don't you go ahead and create a new note.
			%button= link_to "New Note", new_notenote_path

app/views/notenotes/new.html.haml
.wrapper_with_padding
	%h1 New Note
	=render'form' 

app/views/notenotes/show.html.haml
.wrapper_with_padding
	#note_show
		%h1.title= @note.title
		%p= format(@note.content)

		.buttons
			= link_to "Edit", edit_notenote_path, class: "button"
			= link_to "Delete", notenote_path, method: :delete, data: { confirm: "Are you sure?" }, class: "button"

app/views/wellcome/index.html.haml
#banner
	.banner_content
		%h1 NoteNote
		%p Your online notebook. Never forget an idea again.
		%button= link_to "Sign Up", new_user_registration_path
#testimonial
	.wrapper
		%p.quote "The greatest notebook application. Period."
		%p.name - Note
#callouts
	.callout_inner
		.wrapper
			.callout
				%h2 Notes
				%p Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.

			.callout
				%h2 Notes
				%p Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.

			.callout
				%h2 Notes
				%p Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.
#bottom_cta
	.wrapper
		%h2 For Realz!
		%p I want you to sign up... If you don’t. I will find you!
		%button= link_to "Click Meee!!!", new_user_registration_path

%footer
	%p &copy; Note